### ISSUE TITLE
Thank you and package archive

### ISSUE THREAD

**Issue by manuel-uberti** [oantolin/completing-history#2]
Hi,

I just want to say "thank you!" for this package because it greatly simplifies my interaction with <kbd>M-x shell</kbd>, just like `helm-comint-input-ring` did for me.

Any chance you can turn this into a package on (M)ELPA? Note that since I use `straight.el` and `use-package` installing and loading this is already fine with me, but maybe it could help others discover your awesome work if it was available on a package archive.

Your call, of course. :)

**Comment by clemera** [comment]
@oantolin [consult](https://github.com/minad/consult) recently started by @minad is collecting useful completing read commands under a single umbrella, so alternatively you could also consider adding your code there if you like.

**Comment by manuel-uberti** [comment]
Closing this. Feel free to re-open if you want.

(Still happy with the package, of course.)

**Comment by minad** [comment]
@oantolin I wonder about the suggestion regarding consult. I think the commands from this package would fit there. Right now there are already history commands in consult, maybe these could be unified somehow and combined with this?

@manuel-uberti @clemera opinions on this?

**Comment by minad** [comment]
I think I will adopt this, try out a design and ping you on the corresponding PR in the consult repository for comments.

**Comment by oantolin** [comment]
Sorry @manuel-uberti, for dragging my feet on this. I do think that now that the best option is to incorporate this into consult, would that work for you?

Bear in mind that the automatic key binding bit probably wouldn't make it into consult. This package by default bins `M-r` to the completing-history command in a bunch of keymaps, and unbinds `M-s` in those same keymaps (which is an extremely useful prefix I want to always be able to use, not having the default binding for `occur` in shell buffers drove me crazy).

I think what I would do is just add the code to do that binding and unbinding in the Readme here, something like:

"This package works as is, but there is no intention of submitting it to melpa. If you prefer to use a melpa package, you can use the command `consult-buffer-history` from Consult. To get the default bindings `(completing-history-setup-keybinding)` creates, use the following configuration: ..."

**Comment by minad** [comment]
@oantolin Yes, keybinding won't be in consult. But my proposal is mostly ready https://github.com/minad/consult/pull/47. I agree with what you write regarding the readme. I should also add something to the consult readme, which shows how to bind the history command for the relevant modes.

**Comment by manuel-uberti** [comment]
@oantolin It's all fine with me. :)
